name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js (example - adjust for your project)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies (example)
      run: |
        npm ci
        
    - name: Run tests (example)
      run: |
        npm test
